# Generated by Django 4.0.2 on 2022-03-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='lobby name')),
                ('img', models.ImageField(blank=True, upload_to='uploads/%y/%m/%d', verbose_name='lobby image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='uploads/%y/%m/%d', verbose_name='lobby thumbnail')),
                ('followers_count', models.IntegerField(blank=True, default=0, verbose_name='lobby followers count')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='lobby created on')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
