# Generated by Django 4.0.2 on 2022-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_pic_alter_user_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%y/%m/%d', verbose_name='profile pic'),
        ),
    ]
